### ISSUE TITLE
E,NO DATA should or should not be converted in exception?

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#1]

**Comment by Nucs** [comment]
I would suggest wrapping the errors from iqfeed in their own exception class (let's say IQFeedException).
Regarding "E,!NO_DATA!,", if you decide it should throw an exception instead of an empty array, 
you should wrap it in a separate/inherited exception from IQFeedException so it will be possible to distinguish it from.

**Comment by omencat** [comment]
Sorry, I just synced and noticed you already resolved that error pattern

**Comment by mathpaquette** [comment]
Yes I’ll push the code tonight I have it locally!

Sent from my iPhone

On Jul 12, 2018, at 6:31 PM, omencat <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I just synced and noticed you already resolved that error pattern

**Comment by mathpaquette** [comment]
No problem, thanks for raised it. I made a major cleanup/refactor and created custom IQFeed exceptions.

On Jul 12, 2018, at 6:31 PM, omencat <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I just synced and noticed you already resolved that error pattern

**Comment by mathpaquette** [comment]
please review guys

**Comment by omencat** [comment]
confirmed NoDataIQFeedException
