### ISSUE TITLE
Level1 Dynamic Field Type Issue

### ISSUE THREAD

**Issue by GregGamba** [mathpaquette/IQFeed.CSharpApiClient#104]
Dynamic Level1 Streaming, trying use the field "Type" to identify trades vs updates. When I add "Type" to my list of fields it causes all the other data (Bid,Ask,Last etc) to come back weird (1s, and 2s,).

Pic1: Type commented out -- everything works just fine 
![image](https://user-images.githubusercontent.com/11835590/112995351-1ff14100-9139-11eb-90dd-eadc7dcd9a5d.png)

Pic 2: Type included -- everything comes back weird
![image](https://user-images.githubusercontent.com/11835590/112995503-4a42fe80-9139-11eb-857e-752317615681.png)

**Comment by mathpaquette** [comment]
@GregGamba is that the only problematic one you figured out ?

**Comment by GregGamba** [comment]
@mathpaquette, yes it was the only one. Didn't seem to matter what combination of fields were used, once Type was involved everything gets thrown off.

**Comment by mathpaquette** [comment]
@GregGamba did you communicate that with IQFeed or not yet. this is an interesting one. @BunkerCoder did you notice it ?

**Comment by GregGamba** [comment]
@mathpaquette no, tbh with you I have no clue how to deal with this, lol. I figured out a workaround to achieve what I needed and came here in hopes it would help. What did I do?

**Comment by mathpaquette** [comment]
@GregGamba let me get some feedbacks from the folks who are using it and see if it comes from our side or their.

**Comment by mathpaquette** [comment]
most probably the issue comes from us this time.

**Comment by BunkerCoder** [comment]
> 
> 
> @GregGamba did you communicate that with IQFeed or not yet. this is an interesting one. @BunkerCoder did you notice it ?

I'll take a look.

**Comment by BunkerCoder** [comment]
@mathpaquette  - I have a simple fix locally which basically prevents adding Type (throws) to the dynamic field list (but still supports the property to avoid breaking existing client code).  However, I'm fighting an issue in the integration tests that causes my IQFeed Connection Manager to freeze up as soon as it gets to the Level2 tests (I don't have a L2 subscription, and an error window pops that I haven't captured yet). This prevents me from doing mid-session testing because I have live clients that need to collect real-time data.  Once I've had a chance to isolate the issue (and hopefully resolve), I'll do the PR.  (It seems a little pointless with #107 looking good and the simple workaround above, but I'll do it for completeness.)  BTW - I'm on IQFeed Version 6.1.0.20. What version are you using?
