### ISSUE TITLE
Add Level 2

### ISSUE THREAD

**Issue by mathpaquette** [mathpaquette/IQFeed.CSharpApiClient#27]

**Comment by jphiggs** [comment]
Hi, I took the liberty of implementing Level 2 and submitted a PR because this one's been open for a while and I expect you have higher priority demands on your time.  It's mirrored on the Level 1 API and includes tests and an example.  I also included another separate example for retrieving futures chains.  Let me know your thoughts.

**Comment by mathpaquette** [comment]
will be release in version 2
